### ISSUE TITLE
doc inconsistancies in traits.py for gauge traits

### ISSUE THREAD

**Issue by texdarkstar** [evennia/ainneve#109]
According to the [docs](https://github.com/evennia/ainneve/blob/master/world/traits.py) this is what you should see when using `str(character.traits.hp)`:

    >>> hp = character.traits.hp
    >>> str(hp)
    'HP:           10 /   10 ( +0)'

But if you add something to the modifier, it doesn't affect the view of the max:

    >>> hp.mod += 5
    >>> str(hp)
    'HP:           15 /   10 ( +5)'

Note: this is with a gauge trait.
If this is expected and normal, then the docs are inaccurate.
Also, line 199 in [traits.py](https://github.com/evennia/ainneve/blob/master/world/traits.py#L199):

`>>> hp.fill()                          # refill trait`

Shouldn't this be `hp.fill_gauge()`?

Finally, the docs also refer to a `hp.reset()` method, but it doesn't exist.

EDIT: fixed typo

**Comment by aliceafterall** [comment]
Hello! Thanks for opening this issue!

As to the display, this does seem to be a display bug, though the value one has set max to does matter - if one uses `base` as the value instead of `actual`, you might get this behavior. I think this is because our `__str__` method uses `self.actual` and `self.base` as the two values, instead of `self.max` for the second part.

Yes, that should be `.fill_gauge`, there must have previously been a `.fill` method, or perhaps we just made a type initially! Same for `.reset` - however there are `.reset_mod` and `reset_base` options - perhaps those should be mentioned instead.

I'll happily accept a PR to change these things, or I'll make the changes in a bit. Thanks again!

**Comment by friarzen** [comment]
I am going to close this since the game now uses Evennia's Trait Contrib instead of this games original implementation.
