### ISSUE TITLE
Ainneve revival

### ISSUE THREAD

**Issue by ergodicbreak** [evennia/ainneve#116]
Hello all past, present and future contributors to Ainneve. I'm opening this issue to check on the current status of Ainneve and see what people think about an Ainneve revival. Past contributors such as @whitenoiseoss @chainsol and @feend78, feel free to comment, current maintainers such as @friarzen please add your thoughts, and I'm sure there are others I'm missing so please add to the roll call if you can. 

I'm coming at this as someone from the starting team who's been away for a good while, but is now getting back into mudding. My original idea was to build an area for Ainneve as part of mud building month (https://namubumo.com/), so I'm wondering where Ainneve is at currently, and what I could do to contribute to what's needed. 

What is the current status?
* can we delete the legacy branch
* which current issues are important, which can be closed?
* are there critical issues that need to be fixed to be in line with Evennia upstream?

Do people think Ainneve is a worthwhile project to revive?

How do people use Ainneve currently? How could it better serve this purpose? Could it be more useful in other ways?

If you have a specific vision for what Ainneve could be that it currently is not, what big changes should be made to get closer to that vision?

Thanks for your thoughts!

**Comment by friarzen** [comment]
I'll chime in to start with what I stated on IRC.  I do think Ainneve is a valuable project and I think most people have used it as an example on how evmenu, handlers, commands, etc. work, but I think it is actually too complex for it's primary audience.  Hattiehats and petriomelony both quickly chimed in with similar views.

I believe Ainneve provides the most value as a showcase for all of Evennia's functionality and contribs.
There are lots of quality-of-life enhancements that Ainneve can provide an solid example for that are not included in Evennia, containers, stackable items, currency, web character integration, and item auctionhouse, just to name a few.

I also think that Ainneve should use Character Mode 2 by default just to show the difference from Evennia's default mode 0.

**Comment by Griatch** [comment]
To answer the question - yes Ainneve is definitely still valuable as a project. Currently it's mainly used for people to look through and pick out useful snippets. 

I initiated the Ainneve project with the intention of having it be a community project. Therefore I have also deliberately tried to stay hands-off with it. What Ainneve needs is an active, enthusiastic maintainer that stays for the long-haul. Contributors are great, but in the end one person is needed to direct the project and (as is often the case with open initiatives) be ready to have to do the brunt of the work. With such a long time since the last major work being done on this, I'd say the direction to take the game is still pretty much open. Heavy refactoring and cleanup will be needed either way. 

Without giving any strict guidelines (since I, as said, try not to), I think the Ainneve game should likely make use of contribs to a much greater extent, and may even consider feeding back some of its developments as contribs to Evennia core for systems it uses that may be possible to generalize. Conversely, it's probably wise to adopt and use more contribs in the first place so as to not have to reinvent the wheel. 
A notable example of this is what is in the `develop` branch of Evennia (for v1.0) which sports a much more extendable `Trait` as a contrib (heavily inspired by the AInneve version but not 1:1 compatible). While Evennia v1.0 is still a good while out (v0.95 will be released first), and `develop` is not really ready for production, nor is Ainneve at this point, so going bleeding edge and base Ainneve off `develop` may be the way to go at this point. But hey - that's just a suggestion, I won't be doing it. :)

**Comment by ergodicbreak** [comment]
Just a note that I'll be on vacation this week, and I'll have time to respond fully this weekend. However I'm pretty much in alignment with your comments here.

**Comment by kylemecklem** [comment]
I'm always around to help with content writing or creative consulting. 
If you need some flavor text, etc. I'm your man.

**Comment by ChrisLR** [comment]
I agree with switching to Contribs and Develop branch.
Using contribs will save us a lot of time and maintenance, while using the Develop branch might give us a few issues here and there the efforts will contribute to stabilize evennia 1.0 and get it ready faster.

**Comment by friarzen** [comment]
I think we've had enough answers here that I'll go ahead and close this issue, if there is further discussion on features/direction, I'd say it belongs over on the wiki
