### ISSUE TITLE
Add limbs as well as slots

### ISSUE THREAD

**Issue by ergodicbreak** [evennia/ainneve#24]
This is coming up in #20 and I've seen some discussion in IRC. Do we have a good use case for including equipment slots _and_ a separate simulation of limbs? It seems like having both may make integration with combat code slightly easier, if we have effects for targeting/hitting limbs, but I'm not wholly convinced we can't do the same thing with just slots. Your thoughts?

**Comment by time-** [comment]
It depends. Is armor able to take damage? In this case, maybe having limbs _with_ slots is better, as you can hit a specific limb and if it's equiped with a piece of armor, that will be damaged if that's the case.
Otherwise, if we wanna add some more slots that ain't limbs like a light-only slot (ball of light?) or a floating-around slot, it could be coded separately. We'll have limbs **and** slots, limbs are hittable, slots ain't. Another way could be to just keep going with slots and make everything hittable. If I got hit by a fireblast, even my "floating around" may be hit. Some attack skill will have a chance to hit specific limbs, but it will be figurative.

**Comment by ergodicbreak** [comment]
After discussion in IRC with time- and whitenoise, we'll go with slots as described by time- in the previous comment. Character will have slots and limbs. Limbs are hittable slots basically. Non-hittable slots are like earrings, necklace, rings, lightsource, etcetera. We may want a max number on slots so for example you can wear multiple necklaces, or perhaps it makes better sense to just add more slots of the same kind.

**Comment by Nadorrano** [comment]
Ok, I'll take care of that since it's inherent to equip

> We may want a max number on slots so for example you can wear multiple necklaces

That's not an issue, just have neck1 and neck2 both printed as Neck and that's it.

My questions: 
- should "a necklace" take neck1 OR neck2 and a "big neckchain" take neck1 AND neck2?
- Feet, legs, arms and glove slots (slot, not limb!) should be separated (left, right)? This is possible but would be a pain for builders, also if we have limbs so this is not really needed.

Also, the mapping of limbs I suggested in the other thread is the same you describe?
As an example: you hit left leg (limb) --> legs (slot) --> damage equip here
So can link limbs and slots as I shown in #20 ? (also reported below)

``` python
slots = ('head', 'torso', 'feet', 'legs', 'blah', 'blah')
limbs = {'head': 'head'
              'left foot': 'feet',
              'right foot': 'feet'
              'etc': 'etc'}

```

**Comment by Nadorrano** [comment]
We were just two lines of code behind the requested features --> PR #25 . 

Now objects can occupy multiple slots. A small necklace will take one of ['neck1', 'neck2'], a big necklace will take both. To achieve this I added a `slot_operator` attribute to items, which can be 'AND' or 'OR'.
We can also have full body armors that take torso+arms or anything else.
Bonus: two-handed weapons popped out magically after this change is introduced.

I also added char.inventory (property) that returns object that are in contents but not in equip.

Refactored commads a little bit.

Limbs not added yet, I can make a quick commit after someone give me a feedback on  my proposal of mapping them vs equip slots. (see previous post).

**Comment by stefanludlow** [comment]
How should we document gear, considering this change? Is there a preferred
format?

**Comment by Nadorrano** [comment]
I think the building side is not changed, we have typeclasses with slots already defined at "code level".
If you update your list of starting items I will add the corresponding typeclasses, with the slots correctly placed. Just write a loose indication of which slots the item should occupy.

**Comment by stefanludlow** [comment]
Roger. If you have a template of building commands that would be used for
these, I'm happy to put them in that format as well.

**Comment by Nadorrano** [comment]
I think we'll use `@spawn`, or a variation of it.
https://github.com/evennia/evennia/wiki/Spawner
We need to create a file containing templates for every object we have to build (see examples). Every object should be connected to the appropriate typeclass.

**Comment by ergodicbreak** [comment]
@Nadorrano I think that limbs -> slot mapping makes sense. If you get hit in the right foot, we don't want to keep track of damage only to right boot no? So sounds good to me. 

@kaine904 `@spawn` works, its more verbose cousin is @create (see the file https://github.com/evennia/evennia/blob/master/evennia/contrib/tutorial_world/build.ev). Let's move this part of the discussion back to #20

**Comment by Nadorrano** [comment]
> If you get hit in the right foot, we don't want to keep track of damage only to right boot no?

I don't know if I get the meaning of this sentence correctly, however, If we have two boot objects, one per foot, we can keep track of it, if we have "a pair of boots", of course it's a single object and both left and right damage go to the single slot 'feet'. Both are allowed, now it's just a builder thing.

**Comment by ergodicbreak** [comment]
You have the meaning of it, by "don't want" I mean we don't need to track that level of detail. Pair of boots is better for our case.

**Comment by ehussong** [comment]
All numbers in the following post are purely for example and explanation of concepts.

What about adding a sort of..."capacity"...to item slots? For example the multiple necklaces as stated above. Instead of having a neck1/neck2 slot and making "a giant necklace" that takes up both slots - give it a capacity of "bulk" or some sort instead. Eg. Troll Warrior has neck capacity/bulk of 30. He can wear one "giant necklace" of 25 bulk, or 2 necklaces (one 10 bulk and one 12 bulk), or 6 tiny necklaces of 5 bulk each.

I know this probably doesn't make sense for things like gloves or boots directly, but it would allow you to do some interesting things like having giant boots designed for a troll with a bulk of 40. For gnomes you can state that they can't wear boots over the bulk of 25. For boots made for a gnome you can set bulk to 20, and make it so trolls can't equip footwear under the size of 30. Another example could be mages casting. If total bulk > X (strict number based on race) and/or Y% (number based on class) then provide negative debuff to casting damage, fumble effects, etc.

Just a thought that I had when reading the above comments. Apologies if this is too in-depth or already covered by another design doc elsewhere.

**Comment by ergodicbreak** [comment]
So it sounds like a per-slot encumbrance maximum (but also with minimum requirements)? You're right, this is too in-depth for the example game, it could be useful for a more advanced system. 

We do want to add encumbrance, it would be good to open a separate issue for that. 

We do have a size attribute, so we can make eq that requires a minimum size.

**Comment by ergodicbreak** [comment]
Closing as I think we're settled on this issue.

**Comment by ergodicbreak** [comment]
@Nadorrano I just realized we haven't added limbs; can you commit the mapping of limbs -> slots as in https://github.com/evennia/ainneve/issues/24#issuecomment-119951886 ?

**Comment by Nadorrano** [comment]
@ergodicbreak I've been a lot busy in the last days due to my work, I will do this tomorrow!

**Comment by Nadorrano** [comment]
Slots and limbs done, PR #37 

This is a preview:

``` python
        self.slots = (
            'head',
            'left ear',
            'right ear',
            'on eyes',
            'neck1',
            'neck2',
            'shoulders',
            'back',
            'torso',
            'arms',
            'left wrist',
            'right wrist',
            'wield1',
            'wield2',
            'holds',
            'hands',
            'left finger',
            'right finger',
            'belt1',
            'belt2',
            'legs',
            'feet',
        )

        self.limbs = {
            'head':         ('head', 'left ear', 'right ear', 'on eyes', 'neck1', 'neck2',),
            'torso':        ('torso', 'shoulders', 'back', 'belt1', 'belt2',),
            'left arm':     ('arms', 'left wrist',),
            'right arm':    ('arms', 'right wrist',),
            'left hand':    ('hands', 'left finger', 'wield2',),
            'right hand':   ('hands', 'right finger', 'wield1',),
            'left leg':     ('legs',),
            'right leg':    ('legs',),
            'left foot':    ('feet',),
            'right foot':   ('feet',),
        }

```

**Comment by ergodicbreak** [comment]
Great Nadorrano, thanks!
