### ISSUE TITLE
Create automatic NPC stats script

### ISSUE THREAD

**Issue by ergodicbreak** [evennia/ainneve#28]
Using the 'Custom Enemy Stats' table (on the NPCs sheet in this doc, https://docs.google.com/spreadsheets/d/12DVWa-X3J8aXSxRQ5u53gDrFjIGq_gPyQvywxuDhhuU/edit?usp=sharing), write a script that generates acceptable NPC stats. See page 81 (_Creating Custom NPCs_) of the [OA red book](http://www.geekguild.com/openadventure/files/rulebook/v2/openadventure_beta_v2.pdf) for more information. 

Design the script so that it generates random stats following logical templates ('veteran fighter', 'street brawler', 'humble citizen', etcetera). 

Output should be a dictionary of stats (which we'll probably import into Google Sheets, for example see https://github.com/burnash/gspread)

**Comment by knoxx093** [comment]
Request for clarification: "Design the script so that it generates random stats following logical templates ('veteran fighter', 'street brawler', 'humble citizen', etcetera)."

Should the script be given a "template" and then generate stats based on that, or is it just expected to give a proper name to a given set of generated stats? Or am I misunderstanding entirely?

**Comment by ergodicbreak** [comment]
@knoxx093 you've got it right, generate stats based on the template, which would give an acceptable range for each stat.

**Comment by kylemecklem** [comment]
Please note: I have created a far-more robust and detailed "Custom Character Creation Manual" for Open Adventure which is free & open source. This document can be read and followed here: https://github.com/openadventure/Open-Adventure/blob/master/secondary_projects/custom_character_creation_manual/custom_character_creation_manual.pdf

This document should be used rather than the older method as outlined in the discussion above.

Also, please note that I am currently working on creating a set of enemy NPCs the player characters can face within the game. All of my work (including additional Ainneve content) can be found here: https://docs.google.com/document/d/10C6YXdniCYWOX0HlYtR5RW2EBlsqscJBCJnjVr_-0WQ/pub

**Comment by ergodicbreak** [comment]
Thanks @kylemecklem, your doc is looking good.

Mentioning @feend78 here if he'd like to keep up to date on the NPC/eq doc as well.

**Comment by stefanludlow** [comment]
This can be closed as the prototypes_mobs.py covers it. Random stat generation can be accomplished via lambda.

**Comment by feend78** [comment]
Agreed. We have defined a mechanism for handling NPC creation. We will still need to refer to the [character creation manual](https://github.com/openadventure/Open-Adventure/blob/master/secondary_projects/custom_character_creation_manual/custom_character_creation_manual.pdf) as we define NPC prototypes.
