### ISSUE TITLE
Design the combat system

### ISSUE THREAD

**Issue by ergodicbreak** [evennia/ainneve#51]
I wrote a preliminary document based on OA here, https://docs.google.com/document/d/1RQGGoua7Xp0-AAwb75A3MMIaDnnXLCVM3RYVCztiXiI/edit?usp=sharing

**Comment by kylemecklem** [comment]
Related to combat, I have create a set of combat-centric spells. There are a number of tier 0 spells for starting characters, as well as some tier 3 spells which have as of yet been unassigned.

https://docs.google.com/document/d/10C6YXdniCYWOX0HlYtR5RW2EBlsqscJBCJnjVr_-0WQ/edit#

Only two spells are needed for each tier per black and white magic. I made extras so as to have a selection to choose from. I figured the extra spells can be used elsewhere in the game (maybe provided as a magical ability from an enchanted item) or simply discarded.

**Comment by ergodicbreak** [comment]
Per conversations in IRC, we probably are moving to a more RP-centric turn-based combat system.

**Comment by ergodicbreak** [comment]
Note that the draft document is now at https://github.com/evennia/ainneve/wiki/Combat-proposal

**Comment by feend78** [comment]
Items for discussion:
- Turn-based format: OA does an Initiative roll, players take turns in the order determined. Should we instead allow all actions declared at once; resolve combat in order determined by Initiative roll each turn?
- Temporary Damage: Should there be a command to switch a character into "Temporary Damage" mode, or should there be different variants of attack commands to target stamina vs health?
- Is it OK to allow characters to spend their MV points to move on the range field with only one allotment per turn (as opposed to replenishing MV points each half-turn)?
- Aimed Attacks include rolling for a target body part. The OA rules say this can be done for any attacks at the GM's discretion. Do we want it to happen on only aimed attacks? all the time? some other frequency?

I think that's it for now. Please see the [Combat Proposal](https://github.com/evennia/ainneve/wiki/Combat-proposal) wiki page for a more detailed description of the mechanics surrounding these questions.

**Comment by stefanludlow** [comment]
> Aimed Attacks include rolling for a target body part. The OA rules say this can be done for any attacks at the GM's discretion. Do we want it to happen on only aimed attacks? all the time? some other frequency?

Response: Just have an assigned probability of striking any given body location for our first instance. In the future someone can create an aim command that can override it. If we choose not to create this right now, I'd very much encourage us to place a "placeholder" area for this that processes damage and could potentially parse it and echoes out. 

> Is it OK to allow characters to spend their MV points to move on the range field with only one allotment per turn (as opposed to replenishing MV points each half-turn)?

On the turn

> Where do new people coming into combat come in on the rangefield? 

roll 1d2, pick a side. If a group, all go on one side or the other. 

> Do you have to leave the combat instance to leave combat? 

Yes

> Combat between rooms? 

Nope

> Stamina? 

Yes, let's keep it for now, but we should continue discussing. 

> Turn based format: 

Declare actions at beginning phase, and then resolve actions based on order of initiative

**Comment by feend78** [comment]
Notes from IRC conversation:
- MV Points: replenish every turn
- Death to Aimed Attacks
- Yes to Turn-based format with initiative rolls
- Have to escape combat before you can use exits
- Escape "safe time" (escape skill + std_roll()) \* 2 seconds
- Characters must enter combat to be placed on the range field
- For Temporary Damage, a specific command to enter combat along with commands to toggle 'subdue' status
- PPs persist past the end of turns, abilities using them are declared with other turn actions

I've updated the [Combat Proposal](https://github.com/evennia/ainneve/wiki/Combat-proposal) page to reflect our discussion.

**Comment by kylemecklem** [comment]
A slight suggestion to Power Points, rather than killing them outright: simplify and streamline the process so it happens mostly in the background.

Currently, Power Points are special bonus points that appear and disappear throughout combat, sort of like opportunities will appear and disappear in a battle. Seize the moment and you can cause someone's armor to be reduced by 1, or make someone bleed for a few turns, or increase the range of an attack. The player chooses how to allocate their PP since each weapon/armor tends to have a few different choices at various prices.

But if Power Points were handled by the computer, to simply say "When Player has PP => 2, activate Bleed Weapon Ability", the player would just read text that said they "got a 'good' hit in" and now the monster is bleeding and losing additional HP. Likewise monsters could do the same to the PCs.

Keeping things simplified, you'd only need a few basic weapon abilities that slowly make their way into weapons as the player progresses through the game, first the PP cost being high (3+) then eventually less (1-2). If you wanted weapons to have multiple abilities, simply allow the player to "choose" which ability they want to have activated during battle, with the other abilities dormant.

Just my two cents.

**Comment by feend78** [comment]
I like the idea of keeping PPs as @kylemecklem suggests, handling their effects automatically and without player intervention. For equipment with multiple abilities, I agree with allowing the player to select an active effect before or during battle.

**Comment by stefanludlow** [comment]
Agreed

**Comment by feend78** [comment]
Hey there, does anyone builder-ish who is subscribed to this issue want to name a thing?

I have basic combat mostly complete at this point, and I've added some basic death mechanics, but I want to build a shrine or similar as a location for PCs to respawn. I plan to build it to the south of existing Grassy Meadow and main road in Riverport. Would someone like to suggest a name for the respawn location?

**Comment by Griatch** [comment]
Some suggestions: 
1. "The Grassy Knoll"
2. "Shrine of Grass"
3. "The Shrine of the Green lady"
4. "Grass boot hill"

:)

**Comment by feend78** [comment]
OK, I have pushed [this draft](https://github.com/feend78/ainneve/tree/combat) of combat to my account. I'm holding off on creating a pull request because I haven't really had anyone other than me **play-test** it, built any unit tests, or wrote appropriate docstrings in a lot of places. However, if anyone wants to help with the play testing bit, please feel free to clone my branch and give it a try. Note that it depends on a few recent updates to the main Evennia project, so be sure you are running its current _master_ branch locally. 

Thanks to @Griatch for the naming suggestions. ;-)

**Comment by stefanludlow** [comment]
Will see if I can play test this week, traveling on business in SF still.

I like the Grassy Knoll >_>
