### ISSUE TITLE
Implement Commands Based On Medicine Skill

### ISSUE THREAD

**Issue by feend78** [evennia/ainneve#64]
#### OA Origins

In the Open Adventure red book, the _Medicine_ abillity is described as

> “Medicine” is the practice of healing and nurturing. A character who practices medicine can remove adverse conditions or cure certain poisons. 

It is a one round action for which, if the skill test is successful, removes one condition token from the target character, but if failed, the target character must make a will save or lose one HP.

---
#### Ainneve Considerations

However, in Ainneve, we are treating _Medicine_ as a skill, rather than as a single ability, which means there will ideally be a few different commands that are governed by it. For example, we may want to have a separate **heal** command versus **cure poison** or others for individual status effects.

Because these commands will generally target only characters, they should be among the easiest and most straightforward to implement. If you are interested in working on this task, please feel free to discuss your ideas in this issue.

**Comment by tgrgds** [comment]
Hiya, should medicine-related commands be placed in a new file in `commands/skills` or in `combat.py` since it can only be used in combat?

Also, should medicine be its own category in the combat action list?

**Comment by aliceafterall** [comment]
I would suggest `commands/skills`, since you might use it out of combat - let's say "cure poison", for instance. I'm actually unsure of how Ainneve currently treats skills like this, that might be out of combat...
As to medicine skills being their own category in combat, I would say yes to that as well. Just to make it easier to read while in combat!

Oh, you will want to build against develop - it runs on Evennia 0.7, so that will make it a lot easier!

**Comment by InspectorCaracal** [comment]
No longer using Open Adventure; skills should be revisited but this particular issue is no longer relevant.
