### ISSUE TITLE
Unable to Equip Objects

### ISSUE THREAD

**Issue by helix-0311** [evennia/ainneve#69]
https://github.com/evennia/ainneve/blob/master/commands/equip.py#L92

After initial character generation (with a purchase of equipment):

> equip lance
> There is no 'lance' here.
> You have nothing in your equipment.
> 
> inv
> You are carrying:
>  a lance polearm  A sturdy wooden rod fitted with a menacing spike,   (Damage:  4)  
>                   this lance polearm threatens even enemies at a  
>                   distance.  

---

When looking at the code, this seems to be the issue:

equip.py line 92:

```
def func(self):
    caller = self.caller
    args = self.args.strip()
    swap = any(s.startswith('s') for s in self.switches)

    if hasattr(self, "item"):
        obj = self.item
        del self.item
    else:
        **obj = self.caller.search(args) if args else None**
```

---

This else statement always seems to fire, but is not able to find anything in the character's inventory. Tested this (without full debug) by doing:

print args
print obj (after assignment, always None)
print caller
print caller.contents

This verifies that the args are as expected, the obj object is None, the caller is as expected, and the caller.contents contains the object that args should reference. Additionally, tested via the find command with the args string and was able to locate the object with no issue.

**Comment by helix-0311** [comment]
Some additional testing of this item:

```
def func(self):
    caller = self.caller
    args = self.args.strip()
    swap = any(s.startswith('s') for s in self.switches)

    obj = caller.search(args, location=caller)
    print type(caller.contents)
    stuff = caller.contents[0].aliases.all()
    if stuff.__contains__(args):
        print True
    else:
        print False
```

This evaluates to True in the console, making it appear that the caller.search() method is just not inspecting the aliases.

**Comment by helix-0311** [comment]
https://github.com/evennia/evennia/blob/477391b5df650d06b358f1e8587813319a77d120/evennia/contrib/rpsystem.py#L1058

This appears to be the source of the issue.

Superusers are able to access the original search method, while non-superusers are unable to. Not sure the intended purpose of this block, as it would appear to block searches unless certain permission levels are met.

**Comment by feend78** [comment]
Based on Griatch's comments in the parallel issue raised in the evennia repository, the true problem is not this permissions check in the rpsystem module, but that the objects in Ainneve's starter inventory lack the `sdesc` property, which replaces the use of `key` to refer to in-game items. 

The way forward on this is to add sdescs to all of the starter equipment objects. Since they were created with `key` in mind as the primary short description, we could probably just set sdesc to the value of key in the at_object_creation hook on Object. Looking briefly at Object, we have some properties `short_desc` and `long_desc` that should also probably be removed in favor of the rpsystem module's `sdesc`.

**Comment by feend78** [comment]
This issue has been fixed by a commit to the main Evennia library. Please update to the most recent **master** to get the fix. 

The bugfix PR #71 is not related, and was something I just happened upon while looking into this issue.
