### ISSUE TITLE
world/build directory?

### ISSUE THREAD

**Issue by fism** [evennia/ainneve#72]
"Build scripts are in the world/build/ directory and have *.ev or *.py extensions."

There is no world/build directory... am I missing something here?

**Comment by ergodicbreak** [comment]
I thought this might have been left over from an old revision, but didn't see it just now -- where did you see it?

**Comment by fism** [comment]
Limbo

**Comment by feend78** [comment]
We still don't technically have any build scripts in the master, and that note in the Limbo description was added a while ago when that was the planned location for them.

@ergodicbreak , we have since revised the location for build scripts, and in PR #70, the Limbo description has been updated accordingly. We could likely resolve this issue by just merging that PR, if it looks good to you.

**Comment by stefanludlow** [comment]
@feend78

Looks like there are a few minor outstanding issues on the PR you referenced. Let's get those resolved and then let's get this sucker pulled in.

**Comment by feend78** [comment]
This has been addressed in PR #70
