### ISSUE TITLE
Chargen Needs to Allow Exit 

### ISSUE THREAD

**Issue by stefanludlow** [evennia/ainneve#73]
During chargen, if a user is in the middle of their work and needs to quit, there is no option to exit besides manually disconnecting.

**Comment by feend78** [comment]
I guess I'm wondering why we players need to quit in the middle of chargen, but I'm willing to discuss it. 

The thing is, once you've quit chargen, you would just go back to the OOC menu, and attempting to do anything with the character just resumes where they left off. Characters are unplayable in game until they finish chargen because of how movement works, but from that menu, there are other character admin functions you can access... so I could see how it could perhaps be useful.

Do you have something specific in mind? Just wanting to bail and start over on a character?

**Comment by stefanludlow** [comment]
It's definitely a "nice to have," but I'd argue there shouldn't be areas of the game where you can't gracefully exit in some fashion or other as a matter of policy. 

I'd think it'd be sufficient to drop their progress and return them to the ooc menu.

**Comment by Griatch** [comment]
I agree with @stefanludlow that there should be some way to get out of a menu at any time, even if it means loosing progress (as long as this is communicated). The default EvMenu setup has a `quit` command in-built for this reason.

**Comment by feend78** [comment]
Fair enough. For the record, it will not drop their progress, and chargen will pick up wherever they left off when they try to use that character again.

**Comment by feend78** [comment]
This has been implemented in PR #75 , but due to upstream changes that affect unit tests, the Travis output will show errors. The tests have been fixed in PR #70, and it will likely be merged later today. #75 will be merged once the fix is in master.

**Comment by feend78** [comment]
Closed by PR #75
